# Generated by Django 5.2.4 on 2025-07-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_branch_businessinfo_leveltypes_state_employee_branch_and_more'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.leavetype'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.leavestatus'),
        ),
        migrations.AlterUniqueTogether(
            name='leaverequest',
            unique_together={('employee', 'from_date', 'to_date')},
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_allocated', models.IntegerField(default=0)),
                ('used', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype')),
            ],
            options={
                'db_table': 'leave_balance',
                'unique_together': {('employee', 'leave_type')},
            },
        ),
    ]
