# Generated by Django 5.2.4 on 2025-07-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaverequest_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='total_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
