# Generated by Django 5.2.4 on 2025-07-25 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee_is_active'),
        ('leave', '0006_leavesummarylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavelog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_approved_leaves', to='api.employee'),
        ),
        migrations.AddField(
            model_name='leavelog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavelog',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.leavestatus'),
        ),
        migrations.AddField(
            model_name='leavelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='LeaveSummaryLog',
        ),
    ]
