# Generated by Django 5.2.4 on 2025-07-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blacklist_token',
            },
        ),
    ]
