# Generated by Django 5.2.4 on 2025-07-23 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_branch_businessinfo_leveltypes_state_employee_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('acronym', models.CharField(blank=True, max_length=10, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'emp_status',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('check_in_location', models.JSONField(blank=True, null=True)),
                ('check_out_location', models.JSONField(blank=True, null=True)),
                ('check_in_image', models.TextField(blank=True, null=True)),
                ('check_out_image', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('total_working_hour', models.CharField(blank=True, max_length=20, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.employee')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='attendence.employeestatus')),
            ],
            options={
                'db_table': 'Attendance',
                'unique_together': {('employee', 'check_in_date')},
            },
        ),
    ]
