# Generated by Django 5.2.4 on 2025-07-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_branch_businessinfo_leveltypes_state_employee_branch_and_more'),
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='Attendence',
        ),
        migrations.RenameModel(
            old_name='EmployeeStatus',
            new_name='AttendenceStatus',
        ),
    ]
