# Generated by Django 5.2.4 on 2025-07-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee_is_active'),
        ('attendence', '0002_rename_attendance_attendence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendance_sessions',
            },
        ),
        migrations.AlterModelOptions(
            name='attendence',
            options={'ordering': ['check_in_date']},
        ),
        migrations.AddIndex(
            model_name='attendence',
            index=models.Index(fields=['check_in_date'], name='Attendance_check_i_d0d0c8_idx'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendence.attendence'),
        ),
    ]
