# Generated by Django 5.2.4 on 2025-07-25 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee_is_active'),
        ('attendence', '0003_attendancesession_alter_attendence_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendenceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'AttendenceSession',
            },
        ),
        migrations.DeleteModel(
            name='AttendanceSession',
        ),
    ]
