# Generated by Django 5.2.4 on 2025-07-25 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_attendencesession_delete_attendancesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendencesession',
            name='employee',
        ),
        migrations.AddField(
            model_name='attendencesession',
            name='attendence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='attendence.attendence'),
        ),
        migrations.AlterModelTable(
            name='attendencesession',
            table='AttendanceSession',
        ),
    ]
