# Generated by Django 5.2.4 on 2025-07-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0005_remove_attendencesession_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='overtime_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
